# Generated by Django 3.1.7 on 2021-03-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StalkWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start of stalk week')),
                ('end_date', models.DateField(verbose_name='End of stalk week')),
                ('buy_price', models.IntegerField(verbose_name='Turnip buy price')),
            ],
        ),
        migrations.CreateModel(
            name='TurnipStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.IntegerField(verbose_name='Price turnip sold at')),
                ('stalk_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalks.stalkweek')),
            ],
        ),
        migrations.CreateModel(
            name='DayPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(verbose_name='Day of week')),
                ('sell_price_before_noon', models.IntegerField(verbose_name='Sell price before noon')),
                ('sell_price_after_noon', models.IntegerField(verbose_name='Sell price after noon')),
                ('stalk_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalks.stalkweek')),
            ],
        ),
    ]
