# Generated by Django 3.1.7 on 2021-03-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnipstack',
            name='stack_size',
            field=models.IntegerField(default=10, verbose_name='Turnips in a stack'),
        ),
    ]
