# Generated by Django 3.1.7 on 2021-03-14 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0002_turnipstack_stack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnipstack',
            name='sell_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date turnips sold'),
            preserve_default=False,
        ),
    ]
