# Generated by Django 3.1.7 on 2021-03-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0003_turnipstack_sell_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stalkweek',
            old_name='end_date',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='stalkweek',
            old_name='start_date',
            new_name='sunday',
        ),
    ]
