# Generated by Django 3.1.7 on 2021-03-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0004_auto_20210316_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayprices',
            old_name='price_date',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='dayprices',
            old_name='sell_price_before_noon',
            new_name='first_sell_price',
        ),
        migrations.RenameField(
            model_name='dayprices',
            old_name='sell_price_after_noon',
            new_name='last_sell_price',
        ),
    ]
