# Generated by Django 3.1.7 on 2021-03-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0005_auto_20210316_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnipstack',
            name='sell_date',
            field=models.DateField(null=True, verbose_name='Date turnips sold'),
        ),
    ]
