# Generated by Django 3.1.7 on 2021-04-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0006_auto_20210321_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnipStacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnip_stacks', models.IntegerField(verbose_name='Stacks of Turnips Sold')),
                ('stack_size', models.IntegerField(default=10, verbose_name='Turnips in a stack')),
                ('sell_date', models.DateField(null=True, verbose_name='Date turnips sold')),
                ('sell_price', models.IntegerField(verbose_name='Price turnip sold at')),
                ('stalk_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalks.stalkweek')),
            ],
        ),
        migrations.DeleteModel(
            name='TurnipStack',
        ),
    ]
