# Generated by Django 3.1.7 on 2021-04-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalks', '0007_auto_20210402_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnipstacks',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='Price turnip sold at'),
        ),
    ]
